sync:
  - source: alpine:3.17.3
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/alpine:3.17.3
  - source: registry.k8s.io/pause:3.6
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/pause:3.6
  - source: cgr.dev/chainguard/go:latest
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/go:latest
  - source: registry.k8s.io/kube-proxy:v1.26.2
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/kube-proxy:v1.26.2
  - source: alpine:latest
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/alpine:latest
  - source: centos:7
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/centos:7
  - source: ghcr.io/bobymcbobs/gha-sync-scan-and-build/hello@sha256:a61743b19423a01827ba68a1ec81a09d04f84bc69848303905ecbc73824fb88b
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/hello:cool

build:
  - source: ./images/hello/image.yaml
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/hello:latest
    melangeConfigs:
      - ./images/hello/pkg-hello.yaml
  - source: ./images/something/image.yaml
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/something:latest
  - source: ./images/oldschool/Dockerfile
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/oldschool:latest
    dockerOptions:
      context: ./images/oldschool
    sbom:
      artifactName: oldschool
