sync:
  - source: alpine:3.16
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/alpine:3.16
  - source: registry.k8s.io/pause:3.6
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/pause:3.6
  - source: cgr.dev/chainguard/go:latest
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/go:latest
  - source: registry.k8s.io/kube-proxy:v1.26.2
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/kube-proxy:v1.26.2
  - source: alpine:latest
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/alpine:latest
  - source: centos:7
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/centos:7

build:
  - source: ./images/coolthing/image.yaml
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/coolthing:latest
    melangeConfig: ./images/coolthing/melange.yaml
  - source: ./images/something/image.yaml
    destination: ghcr.io/bobymcbobs/gha-sync-scan-and-build/something:latest
