# NOTE refs
# - https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#new-fromjson-method-in-expressions
# - https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script

name: build

on:
  push: {}
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch: {}

permissions:
  id-token: write
  packages: write
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
      - id: set
        run: |
          echo "matrix=$(jq '.build' -r -c <<< "$(yq e . -o json config.yaml)")" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          jq . <<< '${{ steps.prepare.outputs.matrix }}'
  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
      - uses: actions/setup-go@v4
      - uses: sigstore/cosign-installer@main
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo name=date::$(date -u +%Y%m%d) >> $GITHUB_OUTPUT
          echo name=epoch::$(date -u +%s) >> $GITHUB_OUTPUT
        shell: bash
      - uses: chainguard-dev/actions/melange-build@main
        if: ${{ fromJSON(toJSON(matrix)).melangeConfig != '' }}
        with:
          config: ${{ fromJSON(toJSON(matrix)).melangeConfig }}
          sign-with-temporary-key: true
          empty-workspace: true
      - uses: imjasonh/setup-crane@v0.1
      - uses: chainguard-images/actions/apko-publish@main
        id: build-with-signing-key
        name: build-with-signing-key
        if: ${{ fromJSON(toJSON(matrix)).melangeConfig != '' }}
        with:
          tag: ${{ fromJSON(toJSON(matrix)).destination }}
          config: ${{ fromJSON(toJSON(matrix)).source }}
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
          keyring-append: /github/workspace/melange.rsa.pub
      # TODO fix temp hack to conditionally pass keyring-append to apko
      - uses: chainguard-images/actions/apko-publish@main
        if: ${{ fromJSON(toJSON(matrix)).melangeConfig == '' }}
        id: build
        name: build
        with:
          tag: ${{ fromJSON(toJSON(matrix)).destination }}
          config: ${{ fromJSON(toJSON(matrix)).source }}
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
