# NOTE refs
# - https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-your-private-registry

name: scan

on:
  push: {}
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch: {}

permissions:
  security-events: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
      - id: set
        run: |
          echo "matrix=$(jq -r -c '.sync as $sync | .build as $build | [{"destination": $sync[].destination}, {"destination": $build[].destination}]'  <<< "$(yq e . -o json config.yaml)")" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          jq . <<< '${{ steps.prepare.outputs.matrix }}'
  scan:
    if: ${{ fromJSON(needs.prepare.outputs.matrix) != null }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: imjasonh/setup-crane@v0.1
      - name: quay crane login
        env:
          quay-robot-token: ${{ secrets.QUAY_ROBOT_TOKEN }}
          quay-username: ${{ secrets.QUAY_USERNAME }}
        if: ${{ env.quay-robot-token != null && env.quay-username != null }}
        run: |
          echo "${{ env.quay-robot-token }}" | crane auth login --password-stdin quay.io ${{ env.quay-username }}
      - name: get-digests
        id: get-digests
        env:
          SOURCE: ${{ fromJSON(toJSON(matrix)).source }}
          DESTINATION: ${{ fromJSON(toJSON(matrix)).destination }}
        run: |
          SOURCE_DIGEST="$(crane digest "${SOURCE}" || true)"
          DESTINATION_DIGEST="$(crane digest "${DESTINATION}" || true)"
          (
            echo "SOURCE-DIGEST DESTINATION-DIGEST"
            echo "${SOURCE_DIGEST} ${DESTINATION_DIGEST}"
          ) | column -t
          echo "source=${SOURCE_DIGEST}" >> $GITHUB_OUTPUT
          echo "destination=${DESTINATION_DIGEST}" >> $GITHUB_OUTPUT
      - name: Run Trivy vulnerability scanner
        if: ${{ steps.get-digests .outputs.destination != null }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ fromJSON(toJSON(matrix)).destination }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          # format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ steps.get-digests .outputs.destination != null }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
