# NOTE refs
# - https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#new-fromjson-method-in-expressions
# - https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script

name: sync

on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch: {}

permissions:
  packages: write
  actions: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
      - id: set
        run: |
          echo "matrix=$(jq '.sync' -r -c <<< "$(yq e . -o json config.yaml)")" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          jq . <<< '${{ steps.prepare.outputs.matrix }}'
  sync:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
      - uses: imjasonh/setup-crane@v0.1
      - name: determine up-to-date
        env:
          SOURCE: ${{ fromJSON(toJSON(matrix)).source }}
          DESTINATION: ${{ fromJSON(toJSON(matrix)).destination }}
        run: |
          SOURCE_DIGEST="$(crane digest "${SOURCE}")"
          DESTINATION_DIGEST="$(crane digest "${DESTINATION}")"
          if [ "${SOURCE_DIGEST}" = "${DESTINATION_DIGEST}" ]; then
            exit 0
          fi
      - name: copy
        env:
          SOURCE: ${{ fromJSON(toJSON(matrix)).source }}
          DESTINATION: ${{ fromJSON(toJSON(matrix)).destination }}
        run: |
          crane cp $SOURCE $DESTINATION
